const paraBeg=["ffff dddd ssss aaaa ffff dddd ssss aaaa ffff dddd ssss aaaa",
"ff dd ss aa ff dd ss aa ff d ff d ff s ff s ff a ff a",
"juj jyyj joy toy roy try fry juj jyyj joy toy roy try fry juj jyyj joy toy roy try fry fly why",
"asdf asdf asdf asdf asdf asdf asdf asdf asdf asdf",
"fads dafs safd dsaf fasd adfs sdaf afds fdsa",
"jjj kkk lll ;;; jjj kkk lll ;;; jjj kkk lll ;;;jj kk ll ;; jj kk ll ;;",
"jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl; jkl;",
"all fall falls alf alfa alfas fad fads salsa ska skald skalds flak flask flasks",
"eddie died; free ride; eddie fired fred; did eddie die; dier rider fried;",
];

const paraEasy=["freddie tried the fridge; the right fridge; keith agreed; the huge free feed;",
"the right judge; the third huge tiger tried; true ruth tried the third free gift;",
"red jug; guide the tight red kite higher; the hired guide urged the rugged hiker;",
"hole whole while whist whistle when trolley trill thrill",
"rolls tolls folds holds shoulders sisters swifter sword",
"yes tough wily willis fought foolishly to destroy freddy kelly;",
"jills silly white dog juke liked toy dolls hiding them in his woody dog house;",
"mouse mousey mount mound mounds mouse mousey mount mound mounds",
"iou ious conscious envious mission missions iou ious conscious envious missions",
"the little brown mouse went round the house which stood beside the high mound;",
"i rested in my house before playing two rounds of golf; would love to win;",
"Look before you cross the street or you might get knocked down.",
"He bought forty five mind thrilling editions to review for his collection."];

const paraMed=[`No one would have believed, in the last years of the nineteenth century, that human affairs were being watched keenly and closely by intelligences greater than man's and yet as mortal as his own;`,
`With infinite complacency men went to and fro over this globe about their little affairs, serene in their assurance of their empire over matter.`,
`It is possible that the infusoria under the microscope do the same.`,
`Yet, across the gulf of space, minds that are to our minds as ours are to those of the beasts that perish, intellects vast and cool and unsympathetic, regarded this earth with envious eyes, and slowly and surely drew their plans against us.`,
`Yet so vain is man, and so blinded by his vanity, that no writer, up to the very end of the nineteenth century, expressed any idea that intelligent life might have developed there far, or indeed at all, beyond its earthly level.`,
`And we men, the creatures who inhabit this earth, must be to them at least as alien and lowly as are the monkeys and lemurs to us.`,
`The intellectual side of man already admits that life is an incessant struggle for existence, and it would seem that this too is the belief of the minds upon Mars.`,
`Their world is far gone in its cooling, and this world is still crowded with life, but crowded only with what they regard as inferior animals.`,
`And before we judge of them too harshly we must remember what ruthless and utter destruction our own species has wrought, not only upon animals, such as the vanished bison and the dodo, but upon its own inferior races.`,
`The Martians seem to have calculated their descent with amazing subtlety their mathematical learning is evidently far in excess of ours and to have carried out their preparations with a well nigh perfect unanimity.`,
`Had our instruments permitted it, we might have seen the gathering trouble far back in the nineteenth century.`,
`As Mars approached opposition, Lavelle of Java set the wires of the astronomical exchange palpitating with the amazing intelligence of a huge outbreak of incandescent gas upon the planet.`,
`In spite of all that has happened since, I still remember that vigil very distinctly: the black and silent observatory, the shadowed lantern throwing a feeble glow upon the floor in the corner, the steady ticking of the clockwork of the telescope, the little slit in the roof an oblong profundity, with the sta dust streaked across it.`,
`As I watched the little star seemed to grow larger and smaller, and to advance and recede, but that was simply that my eye was tired.`,
`Near it in the field, I remember, were three little points of light, three telescopic stars infinitely remote, and all around it was the unfathomable darkness of empty space.`];

const paraDiff=[`"Bah!" said Scrooge, "Humbug!" He had so heated himself with rapid walking in the fog and frost, this nephew of Scrooge's, that he was all in a glow; his face was ruddy and handsome; his eyes sparkled, and his breath smoked again.`,
`"Christmas a humbug, uncle!" said Scrooge's nephew. "You don't mean that, I am sure?"`,
`"I do," said Scrooge. "Merry Christmas! What right have you to be merry? What reason have you to be merry? You're poor enough."`,
`"Come, then," returned the nephew gaily. "What right have you to be dismal? What reason have you to be morose? You're rich enough."`,
`Scrooge having no better answer ready on the spur of the moment, said, "Bah!" again; and followed it up with "Humbug."`,
`"What else can I be," returned the uncle, "when I live in such a world of fools as this? Merry Christmas! Out upon merry Christmas!`,
'Call me Ishmael. Some years ago never mind how long precisely having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation.',
`Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of every funeral I meet; and especially whenever my hypos get such an upper hand of me, that it requires a strong moral principle to prevent me from deliberately stepping into the street, and methodically knocking people's hats off then, I account it high time to get to sea as soon as I can.`,
`With a philosophical flourish Cato throws himself upon his sword; I quietly take to the ship.`,
`There now is your insular city of the Manhattoes, belted round by wharves as Indian isles by coral reefs commerce surrounds it with her surf.`,
`Circumambulate the city of a dreamy Sabbath afternoon. Go from Corlears Hook to Coenties Slip, and from thence, by Whitehall, northward.`,
`What do you see? Posted like silent sentinels all around the town, stand thousands upon thousands of mortal men fixed in ocean reveries.`,
`But these are all landsmen; of week days pent up in lath and plaster tied to counters, nailed to benches, clinched to desks. How then is this? Are the green fields gone? What do they here?`,
`Why, it isn't possible,' said Scrooge, that I can have slept through a whole day and far into another night. It isn't possible that anything has happened to the sun, and this is twelve at noon.'`,
`The idea being an alarming one, he scrambled out of bed, and groped his way to the window. He was obliged to rub the frost off with the sleeve of his dressin gown before he could see anything; and could see very little then.`,
`The planet Mars, I scarcely need remind the reader, revolves about the sun at a mean distance of 140,000,000 miles, and the light and heat it receives from the sun is barely half of that received by this world.`];
